version: '3.8'

services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./script/psql-init.sql:/docker-entrypoint-initdb.d/psql-init.sql
      - postgresql:/var/lib/postgresql/data

  mongodb:
    image: mongo:5.0.19
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: marketplace
    volumes:
      - dbdata6:/data/db
      - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - '5672:5672'
      - '61616:61616'
    environment:
      AMQ_USER: "user"
      AMQ_PASSWORD: "password"

  user-service:
    build: /user-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgresql
      - artemis
      - eureka
      - configuration_server

  product-service:
    build: /product-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - eureka
      - configuration_server

  image-service:
    build: /image-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AMAZON_S3_ACCESSKEY=somekey
      - AMAZON_S3_SECRET=secret
    depends_on:
      - eureka
      - configuration_server

  mail-service:
    build: /mail-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MAIL_USERNAME=edgar54545edgar@gmail.com
      - MAIL_PASSWORD=super_sercret
    depends_on:
      - artemis
      - eureka
      - configuration_server

  gateway:
    build: /gateway
    mem_limit: 512m
    ports:
      - '8181:8181'
    depends_on:
      - eureka
      - configuration_server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: /eureka-server
    mem_limit: 512m
    ports:
      - '8761:8761'

  configuration_server:
    build: /configuration-server
    mem_limit: 512m
    ports:
      - '9191:9191'
    environment:
      - GIT_USERNAME=edgar54545
      - GIT_PASSWORD=supersecret

volumes:
  postgresql:
    driver: local
  dbdata6: