db.createUser(
        {
            "user":"product-service",
            "pwd":"password",
            "roles":[
                {
                    "role":"readWrite",
                    "db":"marketplace"
                }
               ]
        }
 );
